# Generated by Django 5.2.10 on 2026-01-21 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'товар в заказе', 'verbose_name_plural': 'товары в заказе'},
        ),
    ]
